export interface Setting {
    id: number;
    key: 'SHOW_HEALTH_QUESTIONNAIRE' |
    'SHOW_AESTHETIC_INTEREST' |
    'CLIENT_ACCESS_FULL_ACCESS' |
    'SHOW_LETTER_OF_CONSENT' |
    'SHOW_COVID_19' |
    'SEND_CLIENT_WELCOME_EMAIL' |
    'SHOW_2FA' |
    'SEND_CLIENT_EMAILS' |
    'PORTAL_VIEW_DATE_OF_BIRTH' |
    'PORTAL_VIEW_CITY' |
    'PORTAL_VIEW_PHONE' |
    'PORTAL_VIEW_STREET_ADDRESS' |
    'PORTAL_VIEW_PROFILE' |
    'REQUIRED_CONSENT' |
    'PORTAL_VIEW_OCCUPATION' |
    'PORTAL_REQUIRED_OCCUPATION' |
    'PORTAL_VIEW_DATE_OF_BIRTH' |
    'PORTAL_REQUIRED_DATE_OF_BIRTH' |
    'PORTAL_VIEW_CITY' |
    'PORTAL_REQUIRED_CITY' |
    'PORTAL_VIEW_PHONE' |
    'PORTAL_REQUIRED_PHONE' |
    'PORTAL_VIEW_STREET_ADDRESS' |
    'PORTAL_REQUIRED_STREET_ADDRESS' |
    'PORTAL_VIEW_ZIPCODE' |
    'PORTAL_REQUIRED_ZIPCODE' |
    'PORTAL_VIEW_STATE' |
    'PORTAL_REQUIRED_STATE' |
    'PORTAL_VIEW_COUNTRY' |
    'PORTAL_REQUIRED_COUNTRY' |
    'PORTAL_VIEW_PROFILE' |
    'PORTAL_REQUIRED_PROFILE' |
    'SUPER_USER_MAIL_WHEN_CLIENT_REGISTER' |
    'NUMBER_OF_EMPLOYEES'
    ;
    value: string;
    company_id: number;
}