const config = {
    storage: `${process.env.REACT_APP_STORAGE_PATH}/`,
    adminRole: 'admin',
    masterAdminRole: 'master_admin',
    userRole: 'user',
    stripeActive: 'active',
    loginV1: `${process.env.REACT_APP_APP_URL}/v1/login`,
    login: `${process.env.REACT_APP_APP_URL}/v2/login`,
    otpResend: `${process.env.REACT_APP_APP_URL}/v2/resendOtp`,
    register: `${process.env.REACT_APP_APP_URL}/register`,
    forgot: `${process.env.REACT_APP_APP_URL}/forgot`,
    user: `${process.env.REACT_APP_APP_URL}/user`,
    dashboard_box: `${process.env.REACT_APP_APP_URL}/dashboard/boxData`,
    dashboard_graph: `${process.env.REACT_APP_APP_URL}/dashboard/graphData`,

    companyUpdate: `${process.env.REACT_APP_APP_URL}/company/update`,
    companyMasterUpdate: `${process.env.REACT_APP_APP_URL}/company/:id/update`,
    companySingle: `${process.env.REACT_APP_APP_URL}/company/:id`,
    companyUsers: `${process.env.REACT_APP_APP_URL}/company/:id/users`,
    companyDelete: `${process.env.REACT_APP_APP_URL}/company/:id/delete`,
    companyClients: `${process.env.REACT_APP_APP_URL}/company/:id/clients`,
    companyUsage: `${process.env.REACT_APP_APP_URL}/company/usage`,
    companyPublicUsers: `${process.env.REACT_APP_APP_URL}/company/:id/user`,
    companies: `${process.env.REACT_APP_APP_URL}/company`,
    userStore: `${process.env.REACT_APP_APP_URL}/user/store`,
    userUpdate: `${process.env.REACT_APP_APP_URL}/user/:id/update`,
    userDelete: `${process.env.REACT_APP_APP_URL}/user/:id/delete`,
    userRestore: `${process.env.REACT_APP_APP_URL}/user/:id/restore`,
    userAll: `${process.env.REACT_APP_APP_URL}/user/all`,
    treatment: `${process.env.REACT_APP_APP_URL}/treatment`,
    treatmentStore: `${process.env.REACT_APP_APP_URL}/treatment/store`,
    treatmentUpdate: `${process.env.REACT_APP_APP_URL}/treatment/:id/update`,
    treatmentDelete: `${process.env.REACT_APP_APP_URL}/treatment/:id/delete`,
    treatmentRestore: `${process.env.REACT_APP_APP_URL}/treatment/restore`,

    template: `${process.env.REACT_APP_APP_URL}/v2/template`,
    templateStore: `${process.env.REACT_APP_APP_URL}/v2/template/store`,
    templateUpdate: `${process.env.REACT_APP_APP_URL}/v2/template/:id/update`,
    templateDelete: `${process.env.REACT_APP_APP_URL}/v2/template/:id/delete`,
    templateRestore: `${process.env.REACT_APP_APP_URL}/v2/template/:id/restore`,

    letterOfConsent: `${process.env.REACT_APP_APP_URL}/letter_of_consent`,
    letterOfConsentPublic: `${process.env.REACT_APP_APP_URL}/letter_of_consent/:companyId/public`,
    letterOfConsentStore: `${process.env.REACT_APP_APP_URL}/letter_of_consent/store`,
    letterOfConsentRestore: `${process.env.REACT_APP_APP_URL}/letter_of_consent/restore`,
    letterOfConsentUpdate: `${process.env.REACT_APP_APP_URL}/letter_of_consent/:id/update`,
    letterOfConsentDelete: `${process.env.REACT_APP_APP_URL}/letter_of_consent/:id/delete`,
    clientLetterOfConsentStore: `${process.env.REACT_APP_APP_URL}/client_letter_of_consent/:id/store`,
    clientLetterOfConsentUpdate: `${process.env.REACT_APP_APP_URL}/client_letter_of_consent/:id/update`,
    clientLetterOfConsentDelete: `${process.env.REACT_APP_APP_URL}/client_letter_of_consent/:id/delete`,
    supportStore: `${process.env.REACT_APP_APP_URL}/support/store`,

    generalNoteStore: `${process.env.REACT_APP_APP_URL}/general_note/:clientId/store`,
    generalNoteUpdate: `${process.env.REACT_APP_APP_URL}/general_note/:generalNoteId/update`,
    generalNoteDelete: `${process.env.REACT_APP_APP_URL}/general_note/:generalNoteId/delete`,

    clients: `${process.env.REACT_APP_APP_URL}/client`,
    clientSingle: `${process.env.REACT_APP_APP_URL}/client/:id`,
    clientSingleLogs: `${process.env.REACT_APP_APP_URL}/client/:id/logs`,
    clientLogDownload: `${process.env.REACT_APP_APP_URL}/client/:id/logs/download`,
    clientDownload: `${process.env.REACT_APP_APP_URL}/client/:id?download=pdf`,
    clientStore: `${process.env.REACT_APP_APP_URL}/client/store`,
    clientUpdate: `${process.env.REACT_APP_APP_URL}/client/:id/update`,
    clientDelete: `${process.env.REACT_APP_APP_URL}/client/:id/delete`,
    clientPublicStore: `${process.env.REACT_APP_APP_URL}/client/store/public`,
    clientPublicCreate: `${process.env.REACT_APP_APP_URL}/client/create/public`,

    clientProcedureStore: `${process.env.REACT_APP_APP_URL}/v2/client_treatment/:id/store`,
    clientProcedureUpdate: `${process.env.REACT_APP_APP_URL}/v2/client_treatment/:id/update`,

    clientAfterCareTreatmentStore: `${process.env.REACT_APP_APP_URL}/client/:id/after_care_treatment/store`,
    healthStore: `${process.env.REACT_APP_APP_URL}/health_questionnaire/:id/store/new`,
    aestheticStore: `${process.env.REACT_APP_APP_URL}/aesthetic_interest/:id/store/new`,
    covid19Store: `${process.env.REACT_APP_APP_URL}/covid19/:id/store/new`,
    clientAccess: `${process.env.REACT_APP_APP_URL}/client_access`,
    singleClientAccess: `${process.env.REACT_APP_APP_URL}/client_access/:id`,
    onlyClientAccess: `${process.env.REACT_APP_APP_URL}/client_access/:id/access`,
    clientAccessStore: `${process.env.REACT_APP_APP_URL}/client_access/:id/store`,
    setting: `${process.env.REACT_APP_APP_URL}/setting`,
    settingPublic: `${process.env.REACT_APP_APP_URL}/setting/:id/public`,
    settingStore: `${process.env.REACT_APP_APP_URL}/setting/store`,
    subscriptionCreate: `${process.env.REACT_APP_APP_URL}/subscription/create`,
    subscriptionStore: `${process.env.REACT_APP_APP_URL}/subscription/store`,
    subscriptionEdit: `${process.env.REACT_APP_APP_URL}/subscription/edit`,
    subscriptionUpdate: `${process.env.REACT_APP_APP_URL}/subscription/update`,
    subscriptionDelete: `${process.env.REACT_APP_APP_URL}/subscription/delete`,
    questionnairesPublic: `${process.env.REACT_APP_APP_URL}/questionary/public?company_id=:company_id`,
    questionnaires: `${process.env.REACT_APP_APP_URL}/questionary`,
    questionnaire: `${process.env.REACT_APP_APP_URL}/questionary/:id`,
    questionnaireCreate: `${process.env.REACT_APP_APP_URL}/questionary/store`,
    questionnaireUpdate: `${process.env.REACT_APP_APP_URL}/questionary/:id/update`,
    questionnaireDelete: `${process.env.REACT_APP_APP_URL}/questionary/:id/delete`,
    questionnaireQuestions: `${process.env.REACT_APP_APP_URL}/questionary/:questionary/question`,
    questionnaireQuestionCreate: `${process.env.REACT_APP_APP_URL}/questionary/:questionary/question/store`,
    questionnaireQuestionUpdate: `${process.env.REACT_APP_APP_URL}/questionary/:questionary/question/:id/update`,
    questionnaireQuestionDelete: `${process.env.REACT_APP_APP_URL}/questionary/:questionary/question/:id/delete`,

    clientQuestionnaire: `${process.env.REACT_APP_APP_URL}/client/:client/questionary`,
    clientQuestionnaireData: `${process.env.REACT_APP_APP_URL}/client/:client/questionary_data`,

    questionnaireAnswerCreate: `${process.env.REACT_APP_APP_URL}/questionary/:questionary/answer/store`,
    companyLeadUpdate: `${process.env.REACT_APP_APP_URL}/company/lead/store`,

    invite: `${process.env.REACT_APP_APP_URL}/invite`,

    CLIENT_ACCESS_FULL_ACCESS: 'CLIENT_ACCESS_FULL_ACCESS',
    SHOW_HEALTH_QUESTIONNAIRE: 'SHOW_HEALTH_QUESTIONNAIRE',
    SHOW_AESTHETIC_INTEREST: 'SHOW_AESTHETIC_INTEREST',
    SHOW_LETTER_OF_CONSENT: 'SHOW_LETTER_OF_CONSENT',
    SHOW_COVID_19: 'SHOW_COVID_19',
    SEND_CLIENT_WELCOME_EMAIL: 'SEND_CLIENT_WELCOME_EMAIL',

    leadTypes: {
        win: 'win',
        lost: 'lost',
        not_decided: 'not_decided',
    },

    questionTypes: {
        // yes_no: 'Yes/No',
        yes_no_textbox: 'Yes/No with Textbox',
        textbox: 'Textbox',
        // select: 'Selection',
        // multi_select: 'Multi Selection',
        // image: 'Image Drawing',
    },

    questionTypes1: {
        yes_no: {
            text: 'Yes/No',
            value: 'yes_no',
        },
        yes_no_textbox: {
            text: 'Yes/No with Textbox',
            value: 'yes_no_textbox',
        },
        textbox: {
            text: 'Textbox',
            value: 'textbox',
        },
        // select: 'Selection',
        // multi_select: 'Multi Selection',
        // image: 'Image Drawing',
    },
};

export default config;
